# Generated by Django 5.1.4 on 2025-01-06 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakes', models.CharField(choices=[('00', 'All'), ('12', '1/2'), ('13', '1/3'), ('25', '2/5'), ('55', '5/5'), ('510', '5/10'), ('2040', '20/40')], default='13', max_length=20)),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('buy_in', models.IntegerField()),
                ('cash_out', models.IntegerField()),
                ('notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end_session', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(default='Bogata', on_delete=django.db.models.deletion.CASCADE, to='poker.casino')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SessionNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('takeaway', models.TextField(blank=True, max_length=1000, null=True)),
                ('pokersession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Session', to='poker.pokersession')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='poker.tag')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
